// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","parentId":"@@/global-layout","id":"1"},"2":{"path":"/file","parentId":"@@/global-layout","id":"2"},"3":{"path":"/result","parentId":"@@/global-layout","id":"3"},"4":{"path":"/login","parentId":"@@/global-layout","id":"4"},"5":{"path":"/register","parentId":"@@/global-layout","id":"5"},"6":{"path":"/home","parentId":"@@/global-layout","id":"6"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__file__index" */'@/pages/file/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__result__index" */'@/pages/result/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__login__index" */'@/pages/login/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__register__index" */'@/pages/register/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__home__index" */'@/pages/home/index.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'D:/01workspace/aperture/src/layouts/index.tsx')),
},
  };
}
